HAI
   I HAS A m ITZ DIFF OF 6 AN 3
   I HAS A n ITZ 2
VISIBLE SUM OF SUM OF m AN n AN m
VISIBLE DIFF OF m AN n
VISIBLE PRODUKT OF m AN n
VISIBLE QUOSHUNT OF m AN n
VISIBLE MOD OF m AN n
VISIBLE BIGGR OF m AN n
VISIBLE SMALLR OF m AN n
KTHXBYE
