HAI
  I HAS A x ITZ WIN
  I HAS A y ITZ WIN
  I HAS A x1 ITZ 5
  I HAS A y1 ITZ 6
  VISIBLE BOTH OF x AN y
  VISIBLE EITHER OF x AN y
  VISIBLE WON OF x AN y
  VISIBLE NOT x
  VISIBLE ALL OF x AN x AN x AN y MKAY
  VISIBLE ANY OF y AN y AN y AN y MKAY
  VISIBLE ANY OF BOTH OF x AN EITHER OF NOT x AN y AN y AN NOT y MKAY
  VISIBLE BOTH OF x AN EITHER OF NOT x AN y
  VISIBLE "BOTH SAEM 5 AN 8     " BOTH SAEM 5 AN 8
  VISIBLE "BOTH SAEM 5 AN BOTH SAEM 5 AN 5     " BOTH SAEM 5 AN BOTH SAEM 5 AN 5
  VISIBLE "DIFFRINT 5 AN 5     " DIFFRINT 5 AN 5
  VISIBLE "DIFFRINT 5 AN 8     " DIFFRINT 5 AN 8
  VISIBLE BOTH SAEM BIGGR OF x1 AN y1 AN x1
  VISIBLE BOTH SAEM x1 AN SMALLR OF x1 AN y1
  VISIBLE DIFFRINT BIGGR OF x1 AN y1 AN x1
  VISIBLE DIFFRINT x1 AN SMALLR OF x1 AN y1
  VISIBLE "HEY"
KTHXBYE

